---
sidebar: sidebar 
permalink: xcp/xcp-bp-smb-cifs-csv.html 
keywords: csv, data dump 
summary: Der Befehl in diesem Abschnitt gibt Daten im CSV-Format aus.  Sie können die Größenspalte summieren, um die Gesamtgröße der Daten zu erhalten. 
---
= Erstellen einer CSV-Datei aus einer SMB/CIFS-Freigabe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Der folgende Befehl gibt Daten im CSV-Format aus.  Sie können die Größenspalte summieren, um die Gesamtgröße der Daten zu erhalten.

....
xcp scan -match "((now-x.atime) / 3600) > 31*day" -fmt "'{}, {}, {}, {}'.format(relpath, name, strftime(x.atime, '%y-%m-%d-%H:%M:%S'), humanize_size(size))" -preserve-atime  >file.csv
....
Die Ausgabe sollte ähnlich wie dieses Beispiel aussehen:

....
erase\report_av_fp_cdot_crosstab.csvreport_av_fp_cdot_crosstab.csv20-01-29-10:26:2449.6MiB
....
Um bis zu drei Unterverzeichnisse zu scannen und das Ergebnis in sortierter Reihenfolge anzuzeigen, führen Sie den `xcp -du` und geben Sie die Größe auf jeder Verzeichnisebene bis zur Tiefe von drei Unterverzeichnissen aus.

....
./xcp  scan -du -depth 3 NFS_Server_IP:/source_vol
 
....
Zum Sortieren speichern Sie die Informationen in einer CSV-Datei und sortieren Sie die Informationen.

....
xcp scan -match "type == d" -depth 3 -fmt "'{}, {}, {}, {}'.format(name, relpath, size)" NFS_Server_IP:/share > directory_report.csv
....
Dies ist ein benutzerdefinierter Bericht, der die `-fmt` Befehl.  Es durchsucht alle Verzeichnisse und speichert den Namen, den Pfad und die Größe des Verzeichnisses in einer CSV-Datei.  Sie können die Größenspalte aus der Tabellenkalkulationsanwendung sortieren.
