---
sidebar: sidebar 
permalink: xcp/xcp-bp-troubleshooting.html 
keywords: troubleshooting, problems, error 70, 
summary: Dieser Abschnitt enthält Anleitungen zur Fehlerbehebung bei der Datenmigration mit NetApp XCP. 
---
= Fehlerbehebung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt enthält Anleitungen zur Fehlerbehebung bei der Datenmigration mit NetApp XCP.



== Fehler 1: XCP ist mit NFS3-Fehler 70 fehlgeschlagen: veralteter Dateihandle-Fehler im xcp.log

*Grund und Anleitung.*

Hängen Sie den Quellordner ein und überprüfen Sie, ob der Ordner vorhanden ist.  Wenn es nicht existiert oder entfernt wurde, erhalten Sie eine `stale filehandle` Fehler. In diesem Fall können Sie den Fehler ignorieren.



== Fehler 2: NetApp NFS-Zielvolume verfügt über Speicherplatz, aber XCP ist mit NFS3-Fehler 28 fehlgeschlagen: Kein Speicherplatz mehr auf dem Gerät

*Grund und Anleitung.*

. Überprüfen Sie den Speicherplatz des NFS-Zielvolumes, indem Sie den `df` Befehl oder überprüfen Sie den Speicher.
+
....
root@workr-140: USER3# df -h /xcpdest
Filesystem                 Size  Used Avail Use% Mounted on
10.63.150.127:/xcpsrc_vol  4.3T  1.7T  2.6T  40% /xcpsrc_vol
....
. Überprüfen Sie die Inodes im Speichercontroller.
+
....
A800-Node1-2::> volume show -volume xcpdest -fields files,files-used
vserver        volume  files    files-used
-------------- ------- -------- ----------
A800-Node1_vs1 xcpdest 21251126 21251126
A800-Node1-2::>
....
. Wenn Inode verwendet wird, erhöhen Sie die Anzahl der Inodes, indem Sie den folgenden Befehl ausführen:
+
....
A800-Node1-2::> volume modify -volume xcpdest -vserver A800-Node1_vs1 -files 40000000
Volume modify successful on volume xcpdest of Vserver A800-Node1_vs1.
A800-Node1-2::> volume show -volume xcpdest -fields files,files-used
vserver        volume  files    files-used
-------------- ------- -------- ----------
A800-Node1_vs1 xcpdest 39999990 21251126
A800-Node1-2::>
....

