---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-ps-script.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: Dies ist die NetApp ONTAP Lösung zum Konfigurieren, Härten und Validieren eines ONTAP basierten Cyber-Vaults 
---
= Konfigurieren, Analysieren, Cron-Skript
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp hat einelink:https://github.com/NetApp/ransomeware-cybervault-automation["einzelnes Skript, das heruntergeladen werden kann"^] und wird zum Konfigurieren, Überprüfen und Planen von Cyber-Vault-Beziehungen verwendet.



== Was dieses Skript macht

* Cluster-Peering
* SVM-Peering
* DP-Volume-Erstellung
* SnapMirror -Beziehung und Initialisierung
* Härten Sie das für den Cyber Vault verwendete ONTAP -System
* Beenden und Fortsetzen der Beziehung basierend auf dem Übertragungsplan
* Überprüfen Sie die Sicherheitseinstellungen regelmäßig und erstellen Sie einen Bericht, der etwaige Anomalien aufzeigt.




== So verwenden Sie dieses Skript

link:https://github.com/NetApp/ransomeware-cybervault-automation["Laden Sie das Skript herunter"^]und um das Skript zu verwenden, folgen Sie einfach den folgenden Schritten:

* Starten Sie Windows PowerShell als Administrator.
* Navigieren Sie zu dem Verzeichnis, das das Skript enthält.
* Führen Sie das Skript mit `.\` Syntax zusammen mit den erforderlichen Parametern



NOTE: Bitte stellen Sie sicher, dass alle Informationen eingegeben wurden.  Beim ersten Ausführen (Konfigurationsmodus) werden Anmeldeinformationen sowohl für das Produktions- als auch für das neue Cyber-Vault-System abgefragt.  Anschließend werden die SVM-Peerings (falls nicht vorhanden), die Volumes und der SnapMirror zwischen dem System erstellt und initialisiert.


NOTE: Der Cron-Modus kann verwendet werden, um die Ruhephase und Wiederaufnahme der Datenübertragung zu planen.



== Betriebsarten

Das Automatisierungsskript bietet 3 Ausführungsmodi: `configure` , `analyze` Und `cron` .

[source, powershell]
----
if($SCRIPT_MODE -eq "configure") {
        configure
    } elseif ($SCRIPT_MODE -eq "analyze") {
        analyze
    } elseif ($SCRIPT_MODE -eq "cron") {
        runCron
    }
----
* Konfigurieren – Führt die Validierungsprüfungen durch und konfiguriert das System als Air-Gap.
* Analysieren – Automatisierte Überwachungs- und Berichtsfunktion zum Senden von Informationen zu Anomalien und verdächtigen Aktivitäten an Überwachungsgruppen, um sicherzustellen, dass die Konfigurationen nicht abweichen.
* Cron – Um eine getrennte Infrastruktur zu ermöglichen, automatisiert der Cron-Modus die Deaktivierung des LIF und legt die Übertragungsbeziehung still.


Die Übertragung der Daten in diesen ausgewählten Volumes dauert je nach Systemleistung und Datenmenge einige Zeit.

[source, powershell]
----
./script.ps1 -SOURCE_ONTAP_CLUSTER_MGMT_IP "172.21.166.157" -SOURCE_ONTAP_CLUSTER_NAME "NTAP915_Src" -SOURCE_VSERVER "svm_NFS" -SOURCE_VOLUME_NAME "Src_RP_Vol01" -DESTINATION_ONTAP_CLUSTER_MGMT_IP "172.21.166.159" -DESTINATION_ONTAP_CLUSTER_NAME "NTAP915_Destn" -DESTINATION_VSERVER "svm_nim_nfs" -DESTINATION_AGGREGATE_NAME "NTAP915_Destn_01_VM_DISK_1" -DESTINATION_VOLUME_NAME "Dst_RP_Vol01_Vault" -DESTINATION_VOLUME_SIZE "5g" -SNAPLOCK_MIN_RETENTION "15minutes" -SNAPLOCK_MAX_RETENTION "30minutes" -SNAPMIRROR_PROTECTION_POLICY "XDPDefault" -SNAPMIRROR_SCHEDULE "5min" -DESTINATION_CLUSTER_USERNAME "admin" -DESTINATION_CLUSTER_PASSWORD "PASSWORD123"
----